enum TextureKeys {
  Background = "background",
  Sprite = "sprite",
  Building1 = "building-1",
  Window1 = "window-1",
  Window2 = "window-2",
  Bookcase1 = "bookcase-1",
  Bookcase2 = "bookcase-2",
  Coin = "coin",
  Floor = "floor",
  Cloud1 = "cloud1",
  Cloud2 = "cloud2",
  Cloud3 = "cloud3",
  Cat = "Cat",
  Star = "star",
  Gem = "gem",
  SpriteJump = "sprite-jump",
  SpriteDie = "sprite-die",
  Flames = "flames",
  AnimLaser = "animated-laser",
  AnimLaserEnds = "animated-laser-ends",
  Start = "game-start",
}

export default TextureKeys;
