enum TextureKeys {
  Background = "background",
  Sprite = "sprite",
  Building1 = "building-1",
  Window1 = "window-1",
  Window2 = "window-2",
  Bookcase1 = "bookcase-1",
  Bookcase2 = "bookcase-2",
  LaserMiddle = "laser-middle",
  LaserEnd = "laser-end",
  Coin = "coin",
  Floor = "floor",
  Cloud1 = "cloud1",
  Cloud2 = "cloud2",
  Cloud3 = "cloud3",
  Cat = "Cat",
  Star = "star",
  Gem = "gem",
  Test = "test",
  TestJump = "test-jump",
  TestDie = "test-die",
  Dust = "dust",
}

export default TextureKeys;
